In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency
import statsmodels.formula.api as smf

In [3]:
df=pd.read_csv("insurance_claims_clean_V1.csv")

# Missing_values "authority_contacted"

In [4]:
np.round(pd.crosstab(df["authorities_contacted"], df["fraud_reported"], dropna=False, normalize ="index"),2)

fraud_reported            N     Y
authorities_contacted
Ambulance              0.71  0.29
Fire                   0.73  0.27
Other                  0.68  0.32
Police                 0.79  0.21
NaN                    0.93  0.07

In [5]:
np.round(pd.crosstab(df['authorities_contacted'], df['incident_severity'],dropna=False, normalize='index'),2)

incident_severity      Major Damage  Minor Damage  Total Loss  Trivial Damage
authorities_contacted
Ambulance                      0.36          0.32        0.33            0.00
Fire                           0.37          0.34        0.29            0.00
Other                          0.33          0.28        0.39            0.00
Police                         0.20          0.38        0.25            0.17
NaN                            0.00          0.55        0.00            0.45

In [6]:
np.round(pd.crosstab(df['authorities_contacted'], df['police_report_available'],dropna=False),2)

police_report_available   ?   NO  YES
authorities_contacted
Ambulance                69   74   53
Fire                     77   77   69
Other                    73   56   69
Police                   97  100   95
NaN                      27   36   28

# Missing values "collision_type"

In [7]:
np.round(pd.crosstab(df['collision_type'], df['incident_type'],dropna=False),2)

incident_type    Multi-vehicle Collision  ...  Vehicle Theft
collision_type                            ...
?                                      0  ...             94
Front Collision                      115  ...              0
Rear Collision                       152  ...              0
Side Collision                       152  ...              0

[4 rows x 4 columns]

In [8]:
np.round(pd.crosstab(df['collision_type'], df['fraud_reported'],dropna=False),2)

fraud_reported     N   Y
collision_type
?                162  16
Front Collision  184  70
Rear Collision   201  91
Side Collision   206  70

In [9]:
np.round(pd.crosstab(df['incident_type'], df['fraud_reported'],dropna=False),2)

fraud_reported              N    Y
incident_type
Multi-vehicle Collision   305  114
Parked Car                 76    8
Single Vehicle Collision  286  117
Vehicle Theft              86    8

In [10]:
np.round(pd.crosstab(df['incident_type'], df['fraud_reported'],dropna=False, normalize='index'),3)

fraud_reported                N      Y
incident_type
Multi-vehicle Collision   0.728  0.272
Parked Car                0.905  0.095
Single Vehicle Collision  0.710  0.290
Vehicle Theft             0.915  0.085

# Missing values "property_damage"

In [11]:
np.round(pd.crosstab(df['property_damage'], df['fraud_reported'],dropna=False),2)

fraud_reported     N    Y
property_damage
?                257  103
NO               272   66
YES              224   78

In [12]:
np.round(pd.crosstab(df['property_damage'], df['fraud_reported'],dropna=False, normalize='index'),2)

fraud_reported      N     Y
property_damage
?                0.71  0.29
NO               0.80  0.20
YES              0.74  0.26

# Missing values "police_report_available"

In [13]:
np.round(pd.crosstab(df['police_report_available'], df['fraud_reported'],dropna=False, normalize='index'),2)

fraud_reported              N     Y
police_report_available
?                        0.74  0.26
NO                       0.75  0.25
YES                      0.77  0.23

In [14]:
np.round(pd.crosstab(df['police_report_available'], df['fraud_reported'],dropna=False),2)

fraud_reported             N   Y
police_report_available
?                        254  89
NO                       257  86
YES                      242  72

In [15]:
stat, p = chi2_contingency(pd.crosstab(df["fraud_reported"], df["police_report_available"]))[:2]
V_Cramer = np.sqrt(stat/pd.crosstab(df["fraud_reported"],df["police_report_available"]).values.sum())
print("V_Cramer: ", V_Cramer, end="\n\n")
print("p_value : ", p)

V_Cramer:  0.029010416274539097

p_value :  0.6565199966565936

In [ ]:
col_quan = df.select_dtypes(include=['float64', 'int64']).columns
y=df["fraud_reported"]

In [22]:
col_quan

Index(['Unnamed: 0', 'months_as_customer', 'age', 'policy_number',
       'policy_deductable', 'policy_annual_premium', 'umbrella_limit',
       'insured_zip', 'capital_gains', 'capital_loss',
       'incident_hour_of_the_day', 'number_of_vehicles_involved',
       'bodily_injuries', 'witnesses', 'total_claim_amount', 'injury_claim',
       'property_claim', 'vehicle_claim', 'auto_year', 'policy_bind_year',
       'policy_bind_month', 'policy_bind_weekday'],
      dtype='object')

In [23]:
for col in col_quan:
    print(col)
    model=smf.logit(formula='y~col', data = df).fit()
    display(model.summary())

Unnamed: 0

PatsyError: Number of rows mismatch between data argument and col (1000 versus 1)
    y~col
      ^^^