# Data cleansing

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("insurance_claims.csv")
df.columns

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported', '_c39'],
      dtype='object')

In [5]:
# drop column as 100% nan-values
df.drop('_c39', axis=1,inplace= True)

In [6]:
df.columns

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported'],
      dtype='object')

In [7]:
#change to datetime
df["policy_bind_date"]=pd.to_datetime(df['policy_bind_date'])
df["incident_date"]=pd.to_datetime(df['incident_date'])
df[['policy_bind_date', 'incident_date']].dtypes

policy_bind_date    datetime64[ns]
incident_date       datetime64[ns]
dtype: object

In [8]:
#additional columns year, month, date of policy bind date
df['policy_bind_year']=df["policy_bind_date"].dt.year
df['policy_bind_month']=df["policy_bind_date"].dt.month
df['policy_bind_weekday']=df["policy_bind_date"].dt.weekday

In [9]:
#additional columns month, date of incident date as year is 2015 for all cases
df['incident_month']=df["incident_date"].dt.month
df['incident_weekday']=df["incident_date"].dt.weekday

In [10]:
#ensure consistency on column names
rename ={'capital-gains':'capital_gains','capital-loss': 'capital_loss'}
df.rename(columns=rename, inplace=True)

In [11]:
#df.to_csv('insurance_claims_clean_V1.csv')

In [12]:
df

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,policy_bind_year,policy_bind_month,policy_bind_weekday,incident_month,incident_weekday
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,52080,Saab,92x,2004,Y,2014,10,4,1,6
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,3510,Mercedes,E400,2007,Y,2006,6,1,1,2
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,23100,Dodge,RAM,2007,N,2000,9,2,2,6
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,50720,Chevrolet,Tahoe,2014,Y,1990,5,4,1,5
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,4550,Accura,RSX,2009,N,2014,6,4,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,38,941851,1991-07-16,OH,500/1000,1000,1310.80,0,431289,...,61040,Honda,Accord,2006,N,1991,7,1,2,6
996,285,41,186934,2014-01-05,IL,100/300,1000,1436.79,0,608177,...,72320,Volkswagen,Passat,2015,N,2014,1,6,1,5
997,130,34,918516,2003-02-17,OH,250/500,500,1383.49,3000000,442797,...,52500,Suburu,Impreza,1996,N,2003,2,0,1,4
998,458,62,533940,2011-11-18,IL,500/1000,2000,1356.92,5000000,441714,...,36540,Audi,A5,1998,N,2011,11,4,2,3
999,456,60,556080,1996-11-11,OH,250/500,1000,766.19,0,612260,...,3680,Mercedes,E400,2007,N,1996,11,0,2,3

# Chi2 Test

In [16]:
# chi2 test for categorical variables
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [17]:
from scipy.stats import chi2_contingency

def chi2test(df, col, target_col):
    contingency_table = pd.crosstab(df[col], df[target_col])
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    print(f"Chi2 Statistic: {chi2}")
    print(f"P-value: {p}")
    print(f"Degrees of Freedom: {dof}")
    print("Expected Frequencies:")
    print(expected)

# Example usage
for col in df.columns:
    if df[col].dtypes == 'object':
        print('Chi2 test for column:', col)
        chi2test(df, col, 'fraud_reported')
        print('')

Chi2 test for column: policy_state
Chi2 Statistic: 1.022879411786087
P-value: 0.5996316638296726
Degrees of Freedom: 2
Expected Frequencies:
[[254.514  83.486]
 [233.43   76.57 ]
 [265.056  86.944]]

Chi2 test for column: policy_csl
Chi2 Statistic: 2.1369985737735036
P-value: 0.3435236612436183
Degrees of Freedom: 2
Expected Frequencies:
[[262.797  86.203]
 [264.303  86.697]
 [225.9    74.1  ]]

Chi2 test for column: insured_sex
Chi2 Statistic: 0.8149820820596481
P-value: 0.36665138406877407
Degrees of Freedom: 1
Expected Frequencies:
[[404.361 132.639]
 [348.639 114.361]]

Chi2 test for column: insured_education_level
Chi2 Statistic: 1.6882273540205779
P-value: 0.9460265140372582
Degrees of Freedom: 6
Expected Frequencies:
[[109.185  35.815]
 [ 91.866  30.134]
 [120.48   39.52 ]
 [121.233  39.767]
 [108.432  35.568]
 [107.679  35.321]
 [ 94.125  30.875]]

Chi2 test for column: insured_occupation
Chi2 Statistic: 17.659340491516012
P-value: 0.17088761164902544
Degrees of Freedom: 13
Expected Frequencies:
[[48.945 16.055]
 [51.957 17.043]
 [55.722 18.278]
 [57.228 18.772]
 [39.909 13.091]
 [40.662 13.338]
 [70.029 22.971]
 [53.463 17.537]
 [53.463 17.537]
 [64.005 20.995]
 [47.439 15.561]
 [57.228 18.772]
 [58.734 19.266]
 [54.216 17.784]]

Chi2 test for column: insured_hobbies
Chi2 Statistic: 162.31539899334604
P-value: 8.989147139882094e-25
Degrees of Freedom: 19
Expected Frequencies:
[[36.897 12.103]
 [25.602  8.398]
 [36.144 11.856]
 [42.168 13.832]
 [41.415 13.585]
 [34.638 11.362]
 [26.355  8.645]
 [32.379 10.621]
 [42.921 14.079]
 [41.415 13.585]
 [39.156 12.844]
 [40.662 13.338]
 [41.415 13.585]
 [42.921 14.079]
 [35.391 11.609]
 [48.192 15.808]
 [36.897 12.103]
 [30.873 10.127]
 [37.65  12.35 ]
 [39.909 13.091]]

Chi2 test for column: insured_relationship
Chi2 Statistic: 5.389248280971132
P-value: 0.3702430738108002
Degrees of Freedom: 5
Expected Frequencies:
[[128.01   41.99 ]
 [131.022  42.978]
 [133.281  43.719]
 [137.799  45.201]
 [106.173  34.827]
 [116.715  38.285]]

Chi2 test for column: incident_type
Chi2 Statistic: 29.131539725752873
P-value: 2.1013336774786627e-06
Degrees of Freedom: 3
Expected Frequencies:
[[315.507 103.493]
 [ 63.252  20.748]
 [303.459  99.541]
 [ 70.782  23.218]]

Chi2 test for column: collision_type
Chi2 Statistic: 31.365781459155905
P-value: 7.118897790511356e-07
Degrees of Freedom: 3
Expected Frequencies:
[[134.034  43.966]
 [191.262  62.738]
 [219.876  72.124]
 [207.828  68.172]]

Chi2 test for column: incident_severity
Chi2 Statistic: 264.2373497806052
P-value: 5.447033547673708e-57
Degrees of Freedom: 3
Expected Frequencies:
[[207.828  68.172]
 [266.562  87.438]
 [210.84   69.16 ]
 [ 67.77   22.23 ]]

Chi2 test for column: authorities_contacted
Chi2 Statistic: 8.279562949020814
P-value: 0.04057386756745454
Degrees of Freedom: 3
Expected Frequencies:
[[144.03520352  51.96479648]
 [163.87678768  59.12321232]
 [145.5049505   52.4950495 ]
 [214.58305831  77.41694169]]

Chi2 test for column: incident_state
Chi2 Statistic: 16.129183580687762
P-value: 0.01307712904936151
Degrees of Freedom: 6
Expected Frequencies:
[[ 82.83   27.17 ]
 [197.286  64.714]
 [ 17.319   5.681]
 [ 22.59    7.41 ]
 [186.744  61.256]
 [ 82.83   27.17 ]
 [163.401  53.599]]

Chi2 test for column: incident_city
Chi2 Statistic: 2.6105178630461676
P-value: 0.8558997033560567
Degrees of Freedom: 6
Expected Frequencies:
[[114.456  37.544]
 [112.197  36.803]
 [106.173  34.827]
 [109.185  35.815]
 [ 91.866  30.134]
 [100.902  33.098]
 [118.221  38.779]]

Chi2 test for column: incident_location
Chi2 Statistic: 999.9999999999999
P-value: 0.4851314892749025
Degrees of Freedom: 999
Expected Frequencies:
[[0.753 0.247]
 [0.753 0.247]
 [0.753 0.247]
 ...
 [0.753 0.247]
 [0.753 0.247]
 [0.753 0.247]]

Chi2 test for column: property_damage
Chi2 Statistic: 8.031107812635538
P-value: 0.01803296321162173
Degrees of Freedom: 2
Expected Frequencies:
[[271.08   88.92 ]
 [254.514  83.486]
 [227.406  74.594]]

Chi2 test for column: police_report_available
Chi2 Statistic: 0.8416042524220428
P-value: 0.6565199966565936
Degrees of Freedom: 2
Expected Frequencies:
[[258.279  84.721]
 [258.279  84.721]
 [236.442  77.558]]

Chi2 test for column: auto_make
Chi2 Statistic: 13.775924306876272
P-value: 0.3898117167099123
Degrees of Freedom: 13
Expected Frequencies:
[[51.204 16.796]
 [51.957 17.043]
 [54.216 17.784]
 [57.228 18.772]
 [60.24  19.76 ]
 [54.216 17.784]
 [41.415 13.585]
 [50.451 16.549]
 [48.945 16.055]
 [58.734 19.266]
 [60.24  19.76 ]
 [60.24  19.76 ]
 [52.71  17.29 ]
 [51.204 16.796]]

Chi2 test for column: auto_model
Chi2 Statistic: 46.65817014569841
P-value: 0.15826457876312205
Degrees of Freedom: 38
Expected Frequencies:
[[13.554  4.446]
 [21.084  6.916]
 [18.825  6.175]
 [20.331  6.669]
 [27.861  9.139]
 [24.096  7.904]
 [ 9.789  3.211]
 [13.554  4.446]
 [15.06   4.94 ]
 [21.084  6.916]
 [16.566  5.434]
 [15.06   4.94 ]
 [20.331  6.669]
 [18.072  5.928]
 [20.331  6.669]
 [21.084  6.916]
 [15.813  5.187]
 [18.825  6.175]
 [16.566  5.434]
 [15.06   4.94 ]
 [26.355  8.645]
 [24.096  7.904]
 [11.295  3.705]
 [27.108  8.892]
 [15.06   4.94 ]
 [22.59   7.41 ]
 [18.072  5.928]
 [27.861  9.139]
 [24.849  8.151]
 [23.343  7.657]
 [32.379 10.621]
 [ 9.036  2.964]
 [16.566  5.434]
 [15.06   4.94 ]
 [18.072  5.928]
 [17.319  5.681]
 [31.626 10.374]
 [17.319  5.681]
 [12.048  3.952]]

Chi2 test for column: fraud_reported
Chi2 Statistic: 994.6306227240084
P-value: 2.6386276617672524e-218
Degrees of Freedom: 1
Expected Frequencies:
[[567.009 185.991]
 [185.991  61.009]]

In [18]:
# summarize chi2test result in a dataframe
chi2test_results = pd.DataFrame(columns=['column', 'chi2', 'p', 'dof'])

for col in df.columns:
    if df[col].dtypes == 'object':
        contingency_table = pd.crosstab(df[col], df['fraud_reported'])
        chi2, p, dof, expected = chi2_contingency(contingency_table)
        
        # Create a temporary DataFrame for the current result
        temp_df = pd.DataFrame([{'column': col, 'chi2': chi2, 'p': p, 'dof': dof}])
        
        # Use pd.concat to add the temporary DataFrame to the results
        chi2test_results = pd.concat([chi2test_results, temp_df], ignore_index=True)

chi2test_results

# drop columns with p-value > 0.05

/var/folders/0c/8vqq688975gfb6khywww03880000gn/T/ipykernel_34940/1168009053.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  chi2test_results = pd.concat([chi2test_results, temp_df], ignore_index=True)

                     column         chi2              p  dof
0              policy_state     1.022879   5.996317e-01    2
1                policy_csl     2.136999   3.435237e-01    2
2               insured_sex     0.814982   3.666514e-01    1
3   insured_education_level     1.688227   9.460265e-01    6
4        insured_occupation    17.659340   1.708876e-01   13
5           insured_hobbies   162.315399   8.989147e-25   19
6      insured_relationship     5.389248   3.702431e-01    5
7             incident_type    29.131540   2.101334e-06    3
8            collision_type    31.365781   7.118898e-07    3
9         incident_severity   264.237350   5.447034e-57    3
10    authorities_contacted     8.279563   4.057387e-02    3
11           incident_state    16.129184   1.307713e-02    6
12            incident_city     2.610518   8.558997e-01    6
13        incident_location  1000.000000   4.851315e-01  999
14          property_damage     8.031108   1.803296e-02    2
15  police_report_available     0.841604   6.565200e-01    2
16                auto_make    13.775924   3.898117e-01   13
17               auto_model    46.658170   1.582646e-01   38
18           fraud_reported   994.630623  2.638628e-218    1

# Summary Variables with P<5%

In [20]:

# show columns with p-value < 0.05
chi2test_results[chi2test_results['p'] < 0.05]

                   column        chi2              p dof
5         insured_hobbies  162.315399   8.989147e-25  19
7           incident_type   29.131540   2.101334e-06   3
8          collision_type   31.365781   7.118898e-07   3
9       incident_severity  264.237350   5.447034e-57   3
10  authorities_contacted    8.279563   4.057387e-02   3
11         incident_state   16.129184   1.307713e-02   6
14        property_damage    8.031108   1.803296e-02   2
18         fraud_reported  994.630623  2.638628e-218   1

Alow p-value suggests that there's evidence to support that there is an association between the examined variables.

Statistical Significance vs. Practical Significance:
It's crucial to remember that statistical significance doesn't necessarily imply practical significance. A statistically significant result indicates that the observed association is unlikely to have occurred by chance, but it doesn't tell you how strong or meaningful the association is in real-world terms.
Therefore, even though a variable is statistically significant, it does not mean that it is the most important variable.

##### Implications:
The identified columns are likely to be valuable predictors of your target variable.
They warrant further investigation to understand the nature and strength of their relationship with the target.

##### What to Do Next

1. **Further Analysis:**
Effect Size: Calculate effect size measures (e.g., Cramer's V for chi-squared) to quantify the strength of the association. This will tell you how much of an impact the variable has on the target.
Visualization: Create visualizations (e.g., stacked bar charts, mosaic plots) to visually represent the relationship between the identified columns and the target variable. This can provide valuable insights.
Domain Expertise: Consult with domain experts to understand the practical implications of the findings. Their knowledge can help you interpret the results and determine their relevance.
2. **Feature Selection:**
If you're building a machine learning model, the identified columns are strong candidates for feature selection.
However, be mindful of potential redundancy (as discussed earlier). You may need to use techniques like correlation analysis or VIF to identify and remove highly correlated features.
3. **Model Building:**
Incorporate the significant columns into your predictive models. They are likely to improve the model's accuracy.
4. **Caution and Considerations:**
Multiple Comparisons: When conducting multiple statistical tests, the risk of false positives increases. Consider using methods to adjust p-values for multiple comparisons (e.g., Bonferroni correction).
Data Quality: Ensure that your data is accurate and reliable. Errors in the data can lead to misleading results.
5. **Context:**
 Always interpret the results in the context of your specific problem and domain.



In summary, identifying columns with low p-values is a crucial step in data analysis and feature selection. It highlights variables that are likely to be important, but it's essential to conduct further analysis and consider the practical implications of the findings.

In [ ]:
#drop columns with p-value > 0.05
for col in chi2test_results[chi2test_results['p'] > 0.05]['column']:
    df.drop(col, axis=1, inplace=True)

df.columns